Add deploymentMode flag to deploy-backend
dgraph-io/slash-graphql-cli pull request #5
Opened 2020-10-20 21:03 UTC by nelsonpecora

This allows setting the `deploymentMode` when deploying new backends. Very useful if you want to quickly spin up servers set to "flexible" or "readonly".

2020-10-20 21:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/slash-graphql-cli?pullRequest=5) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/slash-graphql-cli?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/slash-graphql-cli?pullRequest=5) it.</sub>

2020-10-20 21:58 UTC, danielmai requested changes
Other than the flag name change, this looks good to me!

2020-10-20 21:58 UTC, danielmai commented on src/commands/deploy-backend.ts
> +    deploymentMode: flags.string({char: 'm', description: 'Deployment Mode', default: 'graphql'})
To be consistent with flags in other commands, this should be hyphenated as `deployment-mode` instead of `deploymentMode`.

2020-10-21 03:39 UTC, akashjain971 commented
Please add this to the `Readme.md` as well.

2020-10-21 03:50 UTC, merged

2020-10-21 03:50 UTC, gja commented
@akashjain971 the readme is autogenerated on publish